### ISSUE TITLE
"Invalid JSON RPC response: undefined" with the new web3

### ISSUE THREAD

**Issue by asinyagin** [trufflesuite/truffle-artifactor#39]
Hi,

I get the error with the new web3. I think that code should return the response text:
https://github.com/ConsenSys/ether-pudding/blob/5a3f4023bb2b2816086193dce8015eb49193bd5e/classtemplate.js#L11

```
  Provider.prototype.send = function() {
    this.provider.send.apply(this.provider, arguments);
  };
```

because web3 expects it:
https://github.com/ethereum/web3.js/blob/develop/lib/web3/requestmanager.js#L58

```
    var result = this.provider.send(payload);

    if (!Jsonrpc.isValidResponse(result)) {
        throw errors.InvalidResponse(result);
    }
```

**Comment by dotnetspec** [comment]
Hi,
## Environment

* Operating System: Win 10 32 bit
* Truffle version: v3.2.1
* Ethereum client: Geth 1.6.1-unstable
* node version: v7.9.0
* npm version: 4.6.1

I installed
truffle-hdwallet-provider
and updated truffle-config.js in the project directory so it now specifies:
// Allows us to use ES6 in our migrations and tests.
require('babel-register')
var HDWalletProvider = require("truffle-hdwallet-provider");
var mnemonic = "";
module.exports = {
networks: {
development: {
host: 'localhost',
port: 8545,
network_id: '*' // Match any network id
},
ropsten: {
provider: new HDWalletProvider(mnemonic, "https://ropsten.infura.io/"),
network_id: 3
},
rinkeby: {
provider: new HDWalletProvider(mnemonic, "https://www.rinkeby.io/"),
network_id: 4
}
}
}

PS C:\Users\user\Ethereum Projects\truffleprojects\FullStackVoting> truffle console --network rinkeby
events.js:163
      throw er; // Unhandled 'error' event
      ^
Error: Invalid JSON RPC response: "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<tit ..... etc.

There is a rinkeby.json file in the project directory that geth is launched from...

Is it something I'm doing wrong or does it need fixing?

**Comment by dotnetspec** [comment]
Hi,
## Environment

* Operating System: Win 10 32 bit
* Truffle version: v3.2.1
* Ethereum client: Geth 1.6.1-unstable
* node version: v7.9.0
* npm version: 4.6.1

I expect:
to get a trufle console:
Truffle<rinkeby> 

Actual:
I get error below

I installed
truffle-hdwallet-provider
and updated truffle-config.js in the project directory so it now specifies:
// Allows us to use ES6 in our migrations and tests.
require('babel-register')
var HDWalletProvider = require("truffle-hdwallet-provider");
var mnemonic = "";
module.exports = {
networks: {
development: {
host: 'localhost',
port: 8545,
network_id: '*' // Match any network id
},
ropsten: {
provider: new HDWalletProvider(mnemonic, "https://ropsten.infura.io/"),
network_id: 3
},
rinkeby: {
provider: new HDWalletProvider(mnemonic, "https://www.rinkeby.io/"),
network_id: 4
}
}
}

I initialised rinkeby:
geth --datadir=$HOME/.rinkeby --light init rinkeby.json
(There is a rinkeby.json file in the $HOME/.rinkeby directory)

I synced the rinkeby blockchain:
geth --networkid=4 --datadir=$HOME/.rinkeby --syncmode=light --ethstats='yournode:Respect my authoritah!@stats.rinkeby.io' --bootnodes=enode://a24ac7c5484ef4ed0c5eb2d36620ba4e4aa13b8c84684e1b4aab0cebea2ae45cb4d375b77eab56516d34bfbd3c1a833fc51296ff084b770b94fb9028c4d25ccf@52.169.42.101:30303?discport=30304

But 'truffle console --network rinkeby' throws error:

PS C:\Users\user\Ethereum Projects\truffleprojects\FullStackVoting> truffle console --network rinkeby
events.js:163
      throw er; // Unhandled 'error' event
      ^
Error: Invalid JSON RPC response: "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<tit ..... etc.

I can attach to the blockchain via geth, but I need to attach through truffle.

My rinkeby metamask account is open, funded and active in Chrome.

Most of the truffle commands are producing this same error message.

Is it something I'm doing wrong or is it a bug?

**Comment by tcoulter** [comment]
Closing this one for housekeep; the two errors listed are similar, but slightly different. We'll be improving this error message in the future. Please see #489.
