### ISSUE TITLE
Let built pudding contracts inherit from, not redefine, basic methods

### ISSUE THREAD

**Issue by flyswatter** [trufflesuite/truffle-artifactor#42]
I was just looking through the contract objects that pudding generates, and found a fair amount of duplicate code between them.  Each contract has about 14kb of boilerplate that seems like it could be imported from a single module, or defined as a single class to inherit from.

Curious your thoughts!

**Comment by tcoulter** [comment]
This has already been fixed with `truffle-contract`. Closing! Thanks Dan!
