### ISSUE TITLE
better interface for sending money to a contract

### ISSUE THREAD

**Issue by maraoz** [trufflesuite/truffle-artifactor#44]
Current best practice for sending money to a contract via fallback function is: (AFAIK)
```
web3.eth.sendTransaction({to: contract.address, value: 100, from: accounts[0]});
```

I propose the following alternatives:
```
contract.sendTransaction({value: 100})
```

```
contract.fallback({value: 100})
```

**Comment by zmitton** [comment]
A lot of this stuff has been added and moved into `truffle-contract`
https://github.com/trufflesuite/truffle-contract#sending-ether--triggering-the-fallback-function

**Comment by maraoz** [comment]
Awesome!

**Comment by tcoulter** [comment]
Yep. Added! Cheers!
