### ISSUE TITLE
Interface with storage layers

### ISSUE THREAD

**Issue by Schaeff** [trufflesuite/truffle-artifactor#46]
~Pudding~ truffle-artifactor does a great job interacting with contracts.
Are any ways to interact with storage layers (IPFS, centralized, Swarm) planned as it has been seen in other frameworks?

Something like for example:

```
MyContract.setStorage('ipfs')
MyContract.new({foo: 'bar'}, {from: '0x42'})
```

Truffle could know from the abi that `MyContract` expects bytes, so it would
- push {foo: 'bar'} to ipfs
- call new with the corresponding hash

Even a simpler version that just enables to write to and read from storage could be useful.

**Comment by Schaeff** [comment]
Just found ethereum/web3.js#91 which is quite similar. Would be great to hear your thoughts.

**Comment by tcoulter** [comment]
This is a good feature, but adds quite a bit of coupling with IPFS, which I'd argue isn't mature yet, and isn't the accepted community standard. The best bet would be to create a separate module that extends `truffle-contract` objects with IPFS functionality, at least until the Ethereum community standardizes around IPFS. So I'm going to close this again for now, but we'll reconsider it as storage layers and users needs evolve. Thanks!
